export const mockCompanyDataList = [
  {
    ShopID: 100,
    CompanyName: "jiorgdopbp.Shop",
    ShopName: "jiorgdopbp.Shop",
    Title: "สร้างอนาคตสีเขียว เริ่มต้นด้วยพลังงานแสงอาทิตย์",
    Detail:
      "Jiorgdopbp Solar ก่อตั้งขึ้นในปี พ.ศ. 2557 ด้วยความมุ่งมั่นที่จะนำพลังงานสะอาดจากแสงอาทิตย์มาใช้ให้เกิดประโยชน์สูงสุดในประเทศไทย เราเชี่ยวชาญด้าน การจำหน่ายและติดตั้งระบบโซลาร์เซลล์ครบวงจร ทั้งสำหรับบ้านพักอาศัย ธุรกิจ และโรงงานอุตสาหกรรมตลอดเวลากว่า 10 ปี ที่ผ่านมา เราได้ให้บริการลูกค้ามาแล้วมากกว่า 1,000 โครงการทั่วประเทศ ด้วยทีมวิศวกรและช่างผู้เชี่ยวชาญที่ได้รับการอบรมมาตรฐานสากล เราใส่ใจในทุกขั้นตอน ตั้งแต่การออกแบบระบบที่เหมาะสม การเลือกใช้วัสดุคุณภาพสูง ไปจนถึงการติดตั้งที่ได้มาตรฐาน เพื่อให้ลูกค้าทุกท่านได้รับประสิทธิภาพการผลิตพลังงานสูงสุดและผลตอบแทนที่คุ้มค่าที่สุด",
    Facebook: "jjordgobpb Solar",
    LineID: "@jjordgobpbsolar",
    CompanyEmail: "contact@jjordgobpbsolar.com",
    PhoneCompany: "099-123-4567",
    Website: "https://www.jiorgdopbpsolar.com",
    Profile: "/images/seller/shopLogo.png",
    ShopImages: [
      "/images/seller/store1.png",
      "/images/seller/store2.png",
      "/images/seller/store3.png",
    ],
  },
  {
    ShopID: 101,
    CompanyName: "dtiotop.Shop",
    ShopName: "dtiotop.Shop",
    Title: "คุณภาพเกินราคา อุปกรณ์อิเล็กทรอนิกส์ครบวงจร",
    Detail:
      "Dtiotop เป็นผู้นำเข้าและจัดจำหน่ายอุปกรณ์อิเล็กทรอนิกส์คุณภาพดีจากทั่วโลก เรามีทีมวิศวกรที่พร้อมให้คำแนะนำด้านเทคนิค และบริการหลังการขายที่ใส่ใจ...",
    Facebook: "dtiotop Shop",
    LineID: "@dtiotop",
    CompanyEmail: "support@dtiotop.com",
    PhoneCompany: "088-456-7890",
    Website: "https://www.dtiotop.com",
    Profile: "/public/images/allshop/dtiotop.jpg",
    ShopImages: [
      "/public/images/allshop/jqftggikh.jpg",
      "/public/images/allshop/jqftggikh.jpg",
      "/public/images/allshop/jqftggikh.jpg",
      "/public/images/allshop/jqftggikh.jpg",
      "/public/images/allshop/jqftggikh.jpg",
    ],
  },
  {
    ShopID: 102,
    CompanyName: "olujtgfs.Shop",
    ShopName: "olujtgfs.Shop",
    Title: "เครื่องใช้ไฟฟ้าราคาถูก ส่งตรงจากโรงงาน",
    Detail:
      "Olujtgfs Shop ให้บริการจัดจำหน่ายเครื่องใช้ไฟฟ้าหลากหลายชนิด ด้วยราคาย่อมเยาและรับประกันสินค้าทุกชิ้น บริการส่งทั่วประเทศ...",
    Facebook: "olujtgfs Shop",
    LineID: "@olujtgfs",
    CompanyEmail: "sales@olujtgfs.com",
    PhoneCompany: "089-654-3210",
    Website: "https://www.olujtgfs.com",
    Profile: "/public/images/allshop/olujtgfs.jpg",
    ShopImages: [
      "/public/images/allshop/olkuyhrfw.jpg",
      "/public/images/allshop/olkuyhrfw.jpg",
      "/public/images/allshop/olkuyhrfw.jpg",
    ],
  },
  {
    ShopID: 103,
    CompanyName: "olkuyhrfw.Shop",
    ShopName: "olkuyhrfw.Shop",
    Title: "โซลูชันเพื่อบ้านอัจฉริยะ พร้อมบริการติดตั้ง",
    Detail:
      "Olkuyhrfw Shop คือผู้ให้บริการระบบบ้านอัจฉริยะครบวงจร ด้วยเทคโนโลยีล้ำสมัยที่ช่วยให้ชีวิตสะดวก ปลอดภัย และประหยัดพลังงาน...",
    Facebook: "olkuyhrfw Smart Home",
    LineID: "@olkuyhrfw",
    CompanyEmail: "info@olkuyhrfw.com",
    PhoneCompany: "095-222-3344",
    Website: "https://www.olkuyhrfw.com",
    Profile: "/public/images/allshop/olkuyhrfw.jpg",
    ShopImages: [
      "/public/images/allshop/qpkjhmnfd.jpg",
      "/public/images/allshop/qpkjhmnfd.jpg",
      "/public/images/allshop/qpkjhmnfd.jpg",
    ],
  },
  {
    ShopID: 104,
  CompanyName: "olujtgfs Co., Ltd.",
  ShopName: "olujtgfs Smart Living",
  Title: "โซลูชันเพื่อบ้านอัจฉริยะ พร้อมบริการติดตั้ง",
  Detail:
    "olujtgfs คือผู้เชี่ยวชาญด้านระบบสมาร์ทโฮม ด้วยนวัตกรรมทันสมัยที่เชื่อมต่อทุกอุปกรณ์ในบ้านให้ควบคุมได้ง่ายเพียงปลายนิ้ว ผ่านสมาร์ตโฟน พร้อมบริการติดตั้งโดยทีมช่างมืออาชีพทั่วประเทศ",
  Facebook: "olujtgfs.shop",
  LineID: "@olujtgfs",
  CompanyEmail: "info@olujtgfs.com",
  PhoneCompany: "095-111-2233",
  Website: "https://www.olujtgfs.com",
  Profile: "/public/images/allshop/olujtgfs.jpg",
    ShopImages: [
      "/public/images/allshop/qpkjhmnfd.jpg",
      "/public/images/allshop/qpkjhmnfd.jpg",
      "/public/images/allshop/qpkjhmnfd.jpg",
    ],
  },
   {
    ShopID: 105,
    CompanyName: "qpkjhmnfd Co., Ltd.",
  ShopName: "qpkjhmnfd SmartTech",
  Title: "โซลูชันเพื่อบ้านอัจฉริยะ พร้อมบริการติดตั้ง",
  Detail:
    "qpkjhmnfd ผู้นำเทคโนโลยีบ้านอัจฉริยะที่เน้นความปลอดภัยและความสะดวกสบาย ติดตั้งง่าย ใช้งานสะดวก ควบคุมทุกอุปกรณ์ภายในบ้านผ่านระบบอัตโนมัติ พร้อมบริการติดตั้งและดูแลหลังการขาย",
  Facebook: "qpkjhmnfd.shop",
  LineID: "@qpkjhmnfd",
  CompanyEmail: "contact@qpkjhmnfd.com",
  PhoneCompany: "095-444-5566",
  Website: "https://www.qpkjhmnfd.com",
  Profile: "/public/images/allshop/qpkjhmnfd.jpg",
    ShopImages: [
      "/public/images/allshop/dtiotop.jpg",
      "/public/images/allshop/dtiotop.jpg",
      "/public/images/allshop/dtiotop.jpg",
    ],
  },
  {
    ShopID: 106,
    CompanyName: "ruouhdfjkgfd Co., Ltd.",
  ShopName: "ruouhdfjkgfd.Shop",
  Title: "โซลูชันเพื่อบ้านอัจฉริยะ พร้อมบริการติดตั้ง",
  Detail:
    "ruouhdfjkgfd ให้บริการระบบบ้านอัจฉริยะที่ออกแบบมาเพื่อการใช้ชีวิตที่สะดวกสบาย ควบคุมได้ทุกที่ทุกเวลา พร้อมบริการติดตั้งอย่างมืออาชีพและการรับประกันสินค้าระยะยาว",
  Facebook: "ruouhdfjkgfd.shop",
  LineID: "@ruouhdfjkgfd",
  CompanyEmail: "support@ruouhdfjkgfd.com",
  PhoneCompany: "095-777-8899",
  Website: "https://www.ruouhdfjkgfd.com",
  Profile: "/public/images/allshop/ruouhdfjkgfd.jpg",
    ShopImages: [
      "/public/images/allshop/dtiotop.jpg",
      "/public/images/allshop/dtiotop.jpg",
      "/public/images/allshop/dtiotop.jpg",
    ],
  },
  {
    ShopID: 107,
    CompanyName: "sdfgkhlugfth Co., Ltd.",
  ShopName: "SmartHome by sdfgkhlugfth",
  Title: "โซลูชันเพื่อบ้านอัจฉริยะ พร้อมบริการติดตั้ง",
  Detail:
    "sdfgkhlugfth นำเสนอเทคโนโลยีบ้านอัจฉริยะที่ครอบคลุมทุกฟังก์ชันการใช้งาน ไม่ว่าจะเป็นการเปิด-ปิดไฟอัตโนมัติ ระบบความปลอดภัย หรือการควบคุมผ่านแอปมือถือ มั่นใจด้วยบริการติดตั้งและดูแลตลอดอายุการใช้งาน",
  Facebook: "sdfgkhlugfth.shop",
  LineID: "@sdfgkhlugfth",
  CompanyEmail: "hello@sdfgkhlugfth.com",
  PhoneCompany: "095-666-7788",
  Website: "https://www.sdfgkhlugfth.com",
  Profile: "/public/images/allshop/sdfgkhlugfth.jpg",
    ShopImages: [
      "/public/images/allshop/loiukjgfgdf.png",
      "/public/images/allshop/ljkfddshop.jpg",
      "/public/images/allshop/dtiotop.jpg",
    ],
  },
];
